mc.version.title = 1.21.9-1.21.10
mc.version.supported = 1.21.9, 1.21.10

fabric.loom = remap

fabric.api.key_mapping = fabric-key-binding-api-v1
fabric.api.item_group = fabric-item-group-api-v1

mixins.extra.client = \
  MixinClientCommonNetworkHandler,\
  StackedItemContentsAccessor,\
  gui.screen.MixinAbstractRecipeBookScreen

preprocessor.mc_version_number = 12110
