mc.version.title = 1.20-1.20.1
mc.version.supported = 1.20, 1.20.1

fabric.loom = remap

fabric.api.key_mapping = fabric-key-binding-api-v1
fabric.api.item_group = fabric-item-group-api-v1

mixins.extra.client = \
  gui.screen.MixinAbstractFurnaceScreen,\
  gui.screen.MixinCraftingTableScreen,\
  gui.screen.MixinInventoryScreen

preprocessor.mc_version_number = 12001
